services:
  - type: web
    name: cps510-dbms
    env: java
    region: oregon
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/cps510-dbms-1.0.0.jar
    envVars:
      - key: PORT
        fromService:
          type: web
          property: port
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

